scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Scrolling distance multiplier.
  multiplier: 3

# Font configuration
font:
  normal:
    family: Source Code Pro
    style: Regular

  bold:
    family: Source Code Pro
    style: Bold

  italic:
    family: Source Code Pro
    style: Italic

  bold_italic:
    family: Source Code Pro
    style: Bold Italic

  size: 11.5

  # Offset is the extra space around each character. `offset.y` can be thought
  # of as modifying the line spacing, and `offset.x` as modifying the letter
  # spacing.
  #offset:
  #  x: 0
  #  y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the
  # right, increasing `y` moves the glyph upward.
  #glyph_offset:
  #  x: 0
  #  y: 0

# Colors (Pencil Dark)
colors:
  # Default Colors
  primary:
    background: '0x212121'
    foreground: '0xf1f1f1'
  # Normal colors
  normal:
    black:   '0x212121'
    red:     '0xc30771'
    green:   '0x10a778'
    yellow:  '0xa89c14'
    blue:    '0x008ec4'
    magenta: '0x523c79'
    cyan:    '0x20a5ba'
    white:   '0xe0e0e0'
  # Bright colors
  bright:
    black:   '0x818181'
    red:     '0xfb007a'
    green:   '0x5fd7af'
    yellow:  '0xf3e430'
    blue:    '0x20bbfc'
    magenta: '0x6855de'
    cyan:    '0x4fb8cc'
    white:   '0xf1f1f1'

# Background opacity
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.90

shell:
  program: zsh
